language: go

go:
  - '1.12'

before_script:
  - sudo sysctl -w net.ipv4.ip_forward=1

services:
  - docker

env:
  global:
    - GO111MODULE=on
    - CGO_ENABLED=0
    - GO_VERSION=1.12
    - secure: "4Bw9EkIKLE69kr/TkQt1vGsxS4fyaTHFt86k/n1zPcegh1mBY0O60uG1ADInysgthbdS70sGXqBEAqiEFpz0Uk+rya+6g2P/nqGt78Gtp3ZpKQIY3lq33NETMdXRv6waF12KilJk5PDOlQdXG6fmn9tnyp510AjAIl8kKhEeTmUJUwE09UnyjFZaI17F3d5Q/oVVih8zZiEQ1vXY59jXmlX1mztDIE7lE4swXlnK6XHM+ego6evwM5tFsXwFX5SEL0LEq2CFPCkQh8MqGTPbxxsgmLgtcqLCPSOzvCsZ+FgqZ8t2GBt1/hR0hMP0gQlNAJAsuyJF7uF4v2feVjMguyBjc2TneIWqkJgmISxHavbP3w7LZslnaTYKL+W1Xtxy9LTLjmkn3cyOUzQQRhE9JE+6AV0dUsTQNmsgDrsyAAED3Ouf1SmG04sST8+pXIrlDcJbsX5pDrCz8utlpJumzB6xs2JK4hG18PFNpN5XB0lvXfPG2bb6bUbIzEZ5FFCITtBRLkMa1E9Ta1DzSclWyHFziIQ8VecRgHe2VH3HFt6OUvcccyRwRSsmL/Zk7mZuo7O9ykXmfkMnEmHBD78XN67OPs5zPjPTUy6Zyae1ibE+178xsTY7dm/W2FTLarjQVUkSzx7WzTO0FuXJ3wA1P2YicmplYFFxDIFoy6FYV0E="
script:
  - curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist

before_deploy:
  - if [[ -n "${DOCKER_LOGIN_USERNAME}" ]] && [[ -n "${DOCKER_LOGIN_PASSWORD}" ]] && [[ -n "${DOCKER_LOGIN_URL}" ]]; then docker login -u "${DOCKER_LOGIN_USERNAME}" -p "${DOCKER_LOGIN_PASSWORD}" "${DOCKER_LOGIN_URL}"; fi
  - export FULL_IMAGE="${DOCKER_LOGIN_URL}/mittwald/kubernetes-replicator"
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist && docker push "${FULL_IMAGE}:latest"
    on:
      tags: false
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
