language: go

dist: bionic

os: linux

go:
  - '1.12'

before_script:
  - sudo sysctl -w net.ipv4.ip_forward=1

services:
  - docker

env:
  global:
    - GO111MODULE=on
    - CGO_ENABLED=0
    - GO_VERSION=1.12
    - HELM_VERSION=v3.1.2
    - secure: "VNMhL0rwbAaiTV3YrERYSN57/EsMbtp6QET0cN0O4LSWlt0SRDBIeKXnL+Ex3Q7BMY+++DPovW4jZcIVnKyKvH5oGCgJ9Ilj6/Vk9GRKuyu5X+XQi4CuY9f70fz5gCb5ESpeLP9LD12Q6tsNrfRVO+zJiqyvjkZJYZAeTOZmL8szoJIDK83foRmVvwGdTQEK6Pq5fnaNXePcDqgywApDu9QMrab6HcoxZ/TZ99sJP7OEZTQIitdjfTQkol8bx34KT9NUvtd1nvMdcXAWaKyraFr4hJJEYIyB9b3rTtHemKQUhaQm3lrvuy0ns8wqNVyGV9u9qSPdtrL0rqdllw3xm3s5Azg7F+cnVBLyUebG/t5QpAipPeknkRKaicbAyjEZJUIrSLyVma1KQo82btmX/CeFlfS2tyNq9OtOfHouYxdrry8FtMH2DlUkFjHpry5E+FYBldUYDh6HGLYpXuk5JJkx5Td3DL2cqJHpYi6OjcENNESsFkg2ONGW6X3fu7khIkpBrnLMeWwGKlnwn2SVuvcfB/mBKK93Rknm2RdJGEYuOazidRjxRvl9y1oEwerx0SaQH5/uI/QwPN0ksVEiXVXD/C/Djp6nBptxnJdXPBl5gqZsSQ2Qd9JVN2B1oXb1wgHBcIO8ikmuKG8/32IJpFeOCSnkYVEjKSVqQ1MtQhs="

install:
  - wget https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
  - tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
  - chmod +x /tmp/helm

script:
  - /tmp/helm template ./deploy/helm-chart/kubernetes-replicator/.
  - /tmp/helm lint ./deploy/helm-chart/kubernetes-replicator/
  - curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist

before_deploy:
  - docker login -u "${DOCKER_LOGIN_USERNAME}" -p "${DOCKER_LOGIN_PASSWORD}" "${DOCKER_LOGIN_URL}"
  - export FULL_IMAGE="${DOCKER_LOGIN_URL}/mittwald/kubernetes-replicator"
deploy:
  - provider: script
    cleanup: false
    script: >-
      curl -sL https://git.io/goreleaser | bash -s -- --snapshot --skip-publish --rm-dist &&
      docker push "${FULL_IMAGE}:latest" &&
      docker push "${FULL_IMAGE}-arm64:latest" &&
      docker push "${FULL_IMAGE}-armv5:latest" &&
      docker push "${FULL_IMAGE}-armv6:latest" &&
      docker push "${FULL_IMAGE}-armv7:latest"
    on:
      tags: false
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: script
    cleanup: false
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
